In [1]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# ===============================
# PATH
# ===============================
MODEL_PATH = "model/uang_mobilenet_lite.h5" 
TEST_PATH = "testing"

IMG_SIZE = (160, 160)
BATCH_SIZE = 32

# ===============================
# LOAD MODEL
# ===============================
model = load_model(MODEL_PATH)

# ===============================
# LOAD DATA TEST (SUDAH NORMALISASI)
# ===============================
test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(
    TEST_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

# ===============================
# TESTING / EVALUASI
# ===============================
loss, accuracy = model.evaluate(test_data, verbose=1)

print("\n📊 HASIL TESTING")
print("Loss     :", loss)
print("Accuracy :", accuracy)

# ===============================
# CONFUSION MATRIX & REPORT
# ===============================
y_true = test_data.classes
y_pred = model.predict(test_data)
y_pred_classes = np.argmax(y_pred, axis=1)

print("\n📄 Classification Report:")
print(classification_report(
    y_true,
    y_pred_classes,
    target_names=test_data.class_indices.keys()
))

print("\n🔢 Confusion Matrix:")
print(confusion_matrix(y_true, y_pred_classes))


Found 280 images belonging to 7 classes.
9/9 ━━━━━━━━━━━━━━━━━━━━ 10s 692ms/step - accuracy: 0.9464 - loss: 0.1600

📊 HASIL TESTING
Loss     : 0.1600455492734909
Accuracy : 0.9464285969734192
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 553ms/step

📄 Classification Report:
              precision    recall  f1-score   support

        1000       0.88      0.93      0.90        40
       10000       0.93      0.97      0.95        40
      100000       0.95      0.97      0.96        40
        2000       1.00      0.90      0.95        40
       20000       1.00      0.90      0.95        40
        5000       0.95      0.95      0.95        40
       50000       0.93      1.00      0.96        40

    accuracy                           0.95       280
   macro avg       0.95      0.95      0.95       280
weighted avg       0.95      0.95      0.95       280


🔢 Confusion Matrix:
[[37  0  1  0  0  1  1]
 [ 1 39  0  0  0  0  0]
 [ 0  0 39  0  0  0  1]
 [ 3  1  0 36  0  0  0]
 [ 1  1  0  0 36  1  1]
 [ 0 